name: Python application

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [windows-latest]
        

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest
      - name: Run Pylint validation
        run: |
         pylint mon_module.py
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C1234567890\",\"text\":\"Hello world\"}'
    # - name: Send email notification
    #  uses: MeryemAjjane/python-tgit@v3
     # with:
      #  server_address: smtp.gmail.com
       # server_port: 465
        #username: ${{ secrets.EMAIL_USERNAME }}
        #password: ${{ secrets.EMAIL_PASSWORD }}
        #subject: CI/CD build status
        #body: ${{ job.status }}
        #from: CI/CD <${{ secrets.NOTIFICATION_EMAIL}}>
        #to: ${{ secrets.NOTIFICATION_EMAIL}}

