name: Python application

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 7

    strategy:
      matrix:
        os: [windows-latest]
        

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Python ✨
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install slack-sdk

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest
      - name: Run Pylint validation
        run: |
         pylint $(git ls-files '*.py')
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD réussite'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #- name: Send Slack notification
       # if: ${{ always() }}
       # uses: actions/checkout@v1
        #with:
         # webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
         # message: |
           # [${{ job.status }}}]

    #  uses: MeryemAjjane/python-tgit@v3
     # with:
      #  server_address: smtp.gmail.com
       # server_port: 465
        #username: ${{ secrets.EMAIL_USERNAME }}
        #password: ${{ secrets.EMAIL_PASSWORD }}
        #subject: CI/CD build status
        #body: ${{ job.status }}
        #from: CI/CD <${{ secrets.NOTIFICATION_EMAIL}}>
        #to: ${{ secrets.NOTIFICATION_EMAIL}}

